export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const GET_USERINFO_REQUEST: 'GET_USERINFO_REQUEST' = 'GET_USERINFO_REQUEST';
export const GET_USERINFO_SUCCESS: 'GET_USERINFO_SUCCESS' = 'GET_USERINFO_SUCCESS';
export const GET_USERINFO_FAILED: 'GET_USERINFO_FAILED' = 'GET_USERINFO_FAILED';

export const UPDATE_USERINFO_REQUEST: 'UPDATE_USERINFO_REQUEST' = 'UPDATE_USERINFO_REQUEST';
export const UPDATE_USERINFO_SUCCESS: 'UPDATE_USERINFO_SUCCESS' = 'UPDATE_USERINFO_SUCCESS';
export const UPDATE_USERINFO_FAILED: 'UPDATE_USERINFO_FAILED' = 'UPDATE_USERINFO_FAILED';

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const USER_CHECK_SUCCESS: 'USER_CHECK_SUCCESS' = 'USER_CHECK_SUCCESS';
export const USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS' = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED: 'USER_AUTH_FAILED' = 'USER_AUTH_FAILED';