export const ADD_OTHER_INGREDIENTS: 'ADD_OTHER_INGREDIENTS' = 'ADD_OTHER_INGREDIENTS';
export const DELETE_OTHER_INGREDIENTS: 'DELETE_OTHER_INGREDIENTS' = 'DELETE_OTHER_INGREDIENTS';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const UPDATE_OTHER_INGREDIENTS: 'UPDATE_OTHER_INGREDIENTS' = 'UPDATE_OTHER_INGREDIENTS';
export const CLEAN_ORDER: 'CLEAN_ORDER' = 'CLEAN_ORDER';
