export const MODALWINDOW_OPEN_ING = 'MODALWINDOW_OPEN_ING';
export const MODALWINDOW_CLOSE_ING = 'MODALWINDOW_CLOSE_ING';
export const MODALWINDOW_OPEN_ORD = 'MODALWINDOW_OPEN_ORD';
export const MODALWINDOW_CLOSE_ORD = 'MODALWINDOW_CLOSE_ORD';


